# Generated by Django 4.0.4 on 2022-04-21 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_product_product_image'),
        ('modules', '0002_category_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatorsalemodule',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_shop', to='shops.shop'),
        ),
        migrations.AlterField(
            model_name='selfsalemodule',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_shop', to='shops.shop'),
        ),
    ]
