# Generated by Django 4.0.4 on 2022-04-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_alter_operatorsalemodule_shop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.CharField(default='https://res.cloudinary.com/dxsy9rszs/image/upload/v1650618501/box/boxFichier_16_zepleq.png', max_length=10000, verbose_name='Image'),
            preserve_default=False,
        ),
    ]
